alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: api
    match:
      path:
        prefix: /api
  - component:
      name: website
    cors:
      allow_origins:
      - prefix: https://internal.example-app.com
    match:
      path:
        prefix: /
name: biensperience
region: nearest available
services:
- environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: gokepelemo/biensperience
  http_port: 3000
  instance_count: 1
  instance_size_slug: professional-xs
  name: api
  build_command: npm install && npm run build
  run_command: node server.js
  source_dir: /
  envs:
  - name: BUCKET_NAME
    value: ${BUCKET_NAME}
  - name: DATABASE_URL
    value: ${DATABASE_URL}
  - name: SECRET
    value: ${SECRET}
  - name: SECRET_ACCESS_KEY
    value: ${SECRET_ACCESS_KEY}
  - name: ACCESS_KEY_ID
    value: ${ACCESS_KEY_ID}
- envs:
  - name: PRODUCTION
    value: true
  - name: NODE_VERSION
    value: 20.7.0
